// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Child1: typeof import('./src/components/keepAliveDemo/child1.vue')['default']
    Child2: typeof import('./src/components/keepAliveDemo/child2.vue')['default']
    Src: typeof import('./src/components/vModelDemo/src/index.vue')['default']
  }
}

export { }
